DATABRICKS_ENDPOINT = "https://7474651855196680.ai-gateway.cloud.databricks.com/mlflow/v1/chat/completions"
DATABRICKS_TOKEN = "dapi4aac3fb68b6123202282134469be3683"
OPENWEATHER_API_KEY = "08d400e9b06bff6e4563bbff864ad4ae"
DATABRICKS_HOST = "dbc-efb575fe-3817.cloud.databricks.com"
DATABRICKS_HTTP_PATH = "/sql/1.0/warehouses/4945f74d9ad52cfb"